name: lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run isort
        run: |
          isort --recursive --check-only smirnoffee
          isort --recursive --check-only examples

      - name: Run black
        run: |
          black smirnoffee --check
          black examples --check

      - name: Run flake8
        run: |
          flake8 smirnoffee
          flake8 examples
